In [1]:
import numpy as np
call = 15



add = []
nm = 0

while call > nm:
    lit = []
    n = 0

    while call > n:
        try:
            n += 1
            lit.append(n)
            add.append(lit)
            nm += 1
        except:
            break
    
    n = 0
   


pizza = np.array(add)
pizza

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7

In [2]:
pizza.copy()
# for i in range(5):
#     print((i+1)* "*")

for i in range(7):
  for j in range(i+1):
    pizza[i][j] = 0

for p in range(7,15):
  for q in range(15-p):
    pizza[p][q] = 0


print(pizza)

[[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  0  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  0  0  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  0  0  0  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  0  0  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  0  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


In [4]:
for i in range(7):
  for j in range(i):
    pizza[j][i] = 0

for p in range(7,15):
  for q in range(15-p):
    pizza[q][p] = 0


print(pizza)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 14 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 13 14 15]
 [ 0  0  0  0  0  0  0  0  0  0  0 12 13 14 15]
 [ 0  0  0  0  0  0  0  0  0  0 11 12 13 14 15]
 [ 0  0  0  0  0  0  0  0  0 10 11 12 13 14 15]
 [ 0  0  0  0  0  0  0  0  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  0  0  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  0  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  0  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  0  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  0  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  0  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
