# 난수

## # 01. 작업 준비

### 패키지 참조

In [1]:
import tensorflow as tf

## # 02. 균둥 분포 난수

  - 일반적으로 각 이벤트의 결과값을 알 수 없는 경우 미래에 발생할 이벤트의 결과값 $x$가 각 예상되는 범위별로 균등한 확률로 일어날 것이라고 예상될 때 사용.

#### 1) 균등 분포 난수의 사용 예

주사위에 대한 확률

  - 200번을 던지고 201번째 주사위를 던진다고 했을 때 201번째 결과값은 앞의 1에서 200번까지 결과값에 영향을 받지 않는다.

  - 201번째 결과값이 1,2,3,4,5,6 각각의 결과값으로 나올 확률을은 6분의 1이며 이는 앞의 1 ~ 200번째 결과값에 영향을 받아 줄어들걷나 늘어나지 않는다는 것이다.

  - 이처럼 미래 결과값이 경험적으로 알수 없을 상황에서 사용하는 것이 균등분포이다.

#### 2) 균등 분포 난수 실험

스칼라 형태의 균등 분포 난수

In [11]:
uni_rnd1 = tf.random.uniform(shape=[], minval = 0, maxval = 100, dtype = tf.int32)
tf.print(uni_rnd1)

74


백터 형태의 균등 분포 난수

In [14]:
uni_rnd2 = tf.random.uniform(shape=[5], minval = 0, maxval = 100, dtype = tf.int32)
tf.print(uni_rnd2)

[6 65 59 34 85]


행렬 형태의 균등 분포 난수

In [16]:
uni_rnd3 = tf.random.uniform(shape = [2,3], minval = 0, maxval = 100, dtype = tf.int32)
tf.print(uni_rnd3)

[[22 42 12]
 [42 38 15]]


텐서 형태의 균등 분포 난수

In [17]:
uni_rnd4 = tf.random.uniform(shape = [2,3,4], minval = 0, maxval = 100, dtype = tf.int32)
tf.print(uni_rnd4)

[[[82 44 64 15]
  [25 35 84 16]
  [94 38 41 95]]

 [[62 55 72 36]
  [58 31 46 46]
  [37 43 2 82]]]


### 3) 랜덤 값을 갖는 행렬 곱 예시

랜덤 값을 갖는 3행 2열의 행렬을 변수 x로 정의

In [19]:
x = tf.Variable(tf.random.uniform([3,2]))
tf.print(x)

[[0.494673371 0.475951195]
 [0.623505473 0.471099734]
 [0.392242193 0.914475203]]


랜덤 값을 갖는 2행 1열의 행렬을 변수 y로 정의

In [20]:
y = tf.Variable(tf.random.uniform([2,1]))
tf.print(y)

[[0.474270463]
 [0.973103523]]


행렬 곱에 대한 연상을 수행하는 노드 정의

In [21]:
expr = tf.matmul(x, y)
tf.print(expr)

[[0.697758734]
 [0.754139066]
 [1.07590795]]


## # 03. 정규 분포 난수

  - 정규 분포란 과거의 축적된 경험적 데이터를 이미 보유하고 있는 상태에서 이용하여 미래에 발생할 결과값 $x$의 각 예상되는 범위별로 발생될 확률을 어느 정도 추정할 수 있을 때 사용

#### 1) 정규 분포 난수의 사용 예시

매장의 매출액 예측

  - 이전 3개월의 매출이 2천만원, 2천백만원, 2천2백만원 빌생한 경우 평균이나 범위에 대한 예측이 가능하다.
  - `평균`에 대한 예측 -> 이번달 매출은 과거 3개월의 매출 평균인 2천백만원으로 예측
  - `범위`에 대한 예측 -> 최소 2천만원 ~ 최대 2천2백만원까지 매출이 발생할 수 있다는 예상이 가능함

로또 추첨

  - 64개의 공 중에서 하나를 랜덤으로 추출하면, 두 번째 랜덤 범위는 첫 번째 추출된 공을 제외한 범위 안에서 생성된다.

  - 만약 로또 추첨시 하나의 공을 뽑아 번호를 확인하고 그 공을 다시 추첨 대상에 포함시켰다면 균등분포 난수가 된다.

#### 2) 정규 분포 난수 실험

  - 정규 분포 난수를 생성할 때는 평균(mean)과 표준편자(stddev)를 지정해야 한다.

스칼라 형태의 정규 분포 난수

In [22]:
normal_rnd1 = tf.random.normal(shape=[], mean=0.0, stddev=1.0)
tf.print(normal_rnd1)

-0.428845316


백터 형태의 정규 분포 난수

In [24]:
normal_rnd2 = tf.random.normal(shape=[5], mean = 0.0, stddev = 1.0)
tf.print(normal_rnd2)

[2.02677655 1.05705845 0.272912145 -1.32053649 -0.37507534]


행렬 형태의 정규 분포 난수

In [25]:
normal_rnd3 = tf.random.normal(shape = [2,3], mean = 0.0, stddev = 1.0)
tf.print(normal_rnd3)

[[-2.33705735 -0.931452274 0.920053422]
 [-0.740029633 0.197942913 0.199730992]]


텐서 형태의 정규 분포 난수

In [26]:
normal_rnd4 = tf.random.normal(shape=[2,3,4], mean = 0.0, stddev = 1.0)
tf.print(normal_rnd4)

[[[-0.792404234 0.0955693424 0.329979777 -0.535071]
  [0.38126424 0.280856699 -1.23502398 1.36010051]
  [-1.02550364 0.744225502 -1.30992484 0.187681779]]

 [[-1.95407665 -0.23362945 1.15840149 1.04969108]
  [0.0228118245 -0.283797413 -0.137058318 0.76933831]
  [-0.334317327 0.654585958 -0.729385555 -0.998300612]]]
